<div class="discount">
    <div class="klarna_discount klarna-default coupon col-xs-12 col-sm-8">
        <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
        <input type="hidden" name="remove" id="remove-coupone" value="0"/>

        <div class="input-box">
            <input form='checkout_form' class="input-text" id="coupon_code" name="coupon_code"
                   placeholder="<?php echo $this->__('Ange din kod') ?>"
                   value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>"/>
            <button id="apply_coupon_btn" type="button"
                    title="<?php echo $this->__('Apply Coupon') ?>" class="button button-small button-action"
                    value="<?php echo $this->__('Apply Coupon') ?>">
                <span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
        </div>
        <div>
            <div id="coupon-success-msg" class="sucesss"></div>
            <div id="coupon-error-msg" class="error"></div>
        </div>
        <div class="lt-buttons-set">
            <?php
            $classRemovedCouponBtn = 'hidden';
            if (strlen($this->getCouponCode())) {
                $classRemovedCouponBtn = '';
            } ?>

            <button id="cancel_coupon_btn" type="button" title="<?php echo $this->__('Cancel Coupon') ?>"
                    class="button <?php echo $classRemovedCouponBtn; ?>"
                    value="<?php echo $this->__('Cancel Coupon') ?>">
                <span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
            <?php if (strlen($this->getCouponCode())): ?>
            <?php endif; ?>
        </div>

    </div>
</div>
