<div class="mini-cart">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
        $header_type = Mage::getStoreConfig("mango_settings/header/type", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())
    ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php
        if($header_type == 1 || $header_type == 8){
    ?>
    <a href="javascript:void(0)" class="mybag-link"><i class="icon-mango-cart"></i>
        <span class="cart-qty mobile-none-cart-qty">(<?php echo $_cartQty ?>)</span>
        <span class="cart-qty decstop-none-cart-qty"><?php echo $_cartQty ?></span>
    </a>
    <?php
        } else if($header_type == 10) {
    ?>
    <a href="javascript:void(0)" class="mybag-link"><i class="icon-mango-cart"></i><span class="cart-info"><?php echo $this->__("Shopping Cart"); ?></span><span class="cart-qty"><?php echo $_subtotal ?></span></a>
    <?php
        } else {
    ?>
    <a href="javascript:void(0)" class="mybag-link"><i class="icon-mango-cart"></i><span class="cart-info"><?php echo $this->__("My Cart"); ?></span><span class="cart-qty"><?php echo $_subtotal ?></span></a>
    <?php
        }
    ?>
        <div class="topCartContent block-content" style="display: none;">
            <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
                <?php $_items = $this->getRecentItems() ?>
                <?php if(count($_items)): ?>
                    <ol class="mini-products-list">
                        <?php foreach($_items as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ol>
                    <div class="totals">
                        <span><?php echo $this->__('Total')?>: </span>
                        <span class="price-total"><?php echo $_subtotal ?></span>
                    </div>
                    <div class="actions">
                <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                    <?php if(Mage::getStoreConfig('payment/vaimo_klarna_checkout/active')): ?>
                        <a class="btn btn-default btn-checkout decstop-cart" href="<?php echo $this->getUrl('onestepcheckout'); ?>"><?php echo $this->__('Till Kassan'); ?></a>
                        <a class="btn btn-default btn-checkout mobile-cart" href="<?php echo $this->getUrl('checkout'); ?>onepage"><?php echo $this->__('Till Kassan'); ?></a>
                    <?php else: ?>
                        <a class="btn btn-default btn-checkout decstop-cart" href="<?php echo $this->getCheckoutUrl(); ?>"><?php echo $this->__('Till Kassan'); ?></a>
                        <a class="btn btn-default btn-checkout mobile-cart" href="<?php echo $this->getUrl('checkout'); ?>onepage"><?php echo $this->__('Till Kassan'); ?></a>
                    <?php endif; ?>

                <?php endif; ?>
                        <div class="clearer"></div>
                    </div>
                <?php else: ?>
                    <p class="cart-empty">
                        <?php echo $this->__('You have no items in your shopping cart.'); ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
<script type="text/javascript">
    jQuery(function($){
        $('.mini-cart').mouseover(function(e){
            $(this).children('.topCartContent').fadeIn(200);
            return false;
        }).mouseleave(function(e){
            $(this).children('.topCartContent').fadeOut(200);
            return false;
        });
    });
</script>
</div>
