<?php echo $this->getChildHtml('sticky.nav') ?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block_id = Mage::getStoreConfig('mango_settings/header/static_block', $code);
    $store_language = $this->getChildHtml('store_language');
    echo $store_currency = $this->getChildHtml('store_currency');
    $custom_block = "";
    if($custom_block_id){
        $custom_block = $this->getLayout()->createBlock('cms/block')->setBlockId($custom_block_id)->toHtml();
    }
?>

<script>
	jQuery(document).ready(function() {
		jQuery('#cust-cookies-bar-btn').click(function() {
			jQuery('#cust-cookies-bar').slideToggle("fast");
		});
	});
</script>

<div class="header-container type8">
	<div id="cust-cookies-bar">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cookies_bar')->toHtml() ?>
	</div>

	<div id="cust-top-extra-menu">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_extra_menu')->toHtml() ?>
	</div>

    <div class="container" id="cust-header">
        <div class="header">
            <?php if(Mage::getStoreConfig('mango_settings/header/sticky_header_logo', $code)): ?>
                <?php if(Mage::getStoreConfig('mango_settings/header/sticky_header_logo_img', $code)):?>
                    <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo sticky-logo"><img src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('mango_settings/header/sticky_header_logo_img', $code)); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
                <?php endif; ?>
            <?php endif; ?>
            <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
            <div class="header-right" id="top-header-fixed">
                <?php echo $this->getChildHtml('minicart'); ?>
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><i class="icon-mango-user"></i></a></div>
                    <?php echo $this->getChildHtml('topLinks'); ?>
                </div>
                <div class="search-area">
                    <a href="javascript:void(0);" class="search-icon"><i class="icon-mango-search"></i></a>
                    <?php echo $this->getChildHtml('topSearch'); ?>
                </div>
                <?php echo $this->getChildHtml('topMenu') ?>
                <div class="menu-icon"><a href="javascript:void(0)"><i class="icon-mango-nav-icon"></i></a></div>
                <?php echo $this->getChildHtml("demo_header_tooltip"); ?>
            </div>
			<div id="cust-tax-switch-wrap">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('tax_switcher')->toHtml() ?>
			</div>

            <div class="icom-price-menu">
                <i class="special-price-mobile"></i>
            </div>

            <hr class="mobile-line">

        </div>
    </div>
</div>
<div class="mobile-special-all">
    <?php
    echo $this->getLayout()->createBlock('cms/block')->setBlockId("links_right_block")->toHtml();
    ?>
</div>
<script>
    jQuery('.icom-price-menu').click(function(){
        if(jQuery('.mobile-special-all').hasClass('active')){
            jQuery('.mobile-special-all').removeClass('active');
        }else{
            jQuery('.mobile-special-all').addClass('active');
        }
    })
</script>
<?php echo $this->getChildHtml('mobile.nav') ?>
