<div class="category-products sub-category">
  <ul class="products-grid">
    <?php
    //    $_categories=$this->getCurrentChildCategories();
    //      if($_categories->count()):
    //    $categorycount = 0;
    //      foreach ($_categories as $_category):
    //    if($_category->getIsActive()):
    //    $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
    //    $layer = Mage::getSingleton('catalog/layer');
    //    $layer->setCurrentCategory($cur_category);
    //    $catName = $this->getCurrentCategory()->getName();
    //    if ($categorycount == 0){
    //    $class = "first";
    //    }
    //    elseif ($categorycount == 2){
    //    $class = "last";
    //    }
    //    else{
    //    $class = "";
    //    }
    $class = '';
    $layer = Mage::getSingleton('catalog/layer');
    $_helper = $this->helper('catalog/output');
    $_category = $layer->getCurrentCategory();
    $currentCategoryId = $_category->getId();
    $children = Mage::getModel('catalog/category')->getCategories($currentCategoryId);
    foreach ($children as $category) { ?>
      <?php if ($category->getId() == $currentCategoryId) {
        continue;
      }
      $img = Mage::getModel('catalog/category')->load($category->getId());

      ?>
      <li id="<?php echo $category->getId() ?>" class="item sub-item images-item <?= $class ?>">
        <a href="<?php echo $img->getUrl(); ?>"
           title="<?php echo $this->htmlEscape($category->getName()) ?>"><img
              src="<?php echo $img->getImageUrl(); ?>" 
              alt="<?php echo $this->htmlEscape($category->getName()) ?>"/></a>

        <h2><a href="<?php echo $img->getUrl(); ?>"
               title="<?php echo $this->htmlEscape($category->getName()) ?>"><?php echo $this->htmlEscape($category->getName()) ?></a>
        </h2>


      </li>
    <?php }
    ?>
    <?php
    //  endif;
    //  if($categorycount == 2){
    //  $categorycount = 0;
    //  echo "</ul>\n\n<ul class=\"products-grid\">";
    //  }
    //  else{
    //  $categorycount++;
    //  }
    //  endforeach;
    //  endif;
    ?>
  </ul>
</div>

<br>
<div class="baner-category-img">
  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-12 col-sm-6">
        <div class="sub-cat-one">
          <a href="<?php echo $this->getBaseUrl();?>">
            <img src="<?php echo $this->getSkinUrl('images/1test.jpg') ?>" alt="">

            <div class="pos-absolute"></div>
            <p class="pos-absolute-p">Nya Produkter</p>
          </a>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <?php
        $one = false;
        $two = false;
        $i = 0;
        foreach ($children as $category) {
          $children1 = Mage::getModel('catalog/category')->getCategories($category->getId());
          foreach ($children1 as $category1) {
            $categoryImg = Mage::getModel('catalog/category')->load($category1->getId());
            if ($two == false && $one == false) {
              if ($i == 0) {
                echo '<div class="sub-cat-two">';
              }
              if ($i == 2) {
                $two = true;
                break;
              }
              $img = '';
              if ($categoryImg->getImageUrl()) {
                $img = $categoryImg->getImageUrl();
              } else {
                if ($i == 0) {
                  $img = $this->getSkinUrl('images/3test.jpg');
                } else {
                  $img = $this->getSkinUrl('images/4test.jpg');
                }

              }
              echo $one_cat = '<div class="c-two">
                                    <a href="' . $categoryImg->getUrl() . '">
                                    <img src="' . $img . '" alt="' . $categoryImg->getName() . '">

                                        <div class="pos-absolute-c"></div>
                                        <p class="pos-absolute-p sub-cat-text">' . $categoryImg->getName() . '</p>
                                    </a>
                            </div>';
              $i++;
              if ($i == 2) {
                echo '<div style="clear: both"></div>
                            </div>';
              }
            }

            if ($two == true && $one == false) {

              $img = '';
              if ($categoryImg->getImageUrl()) {
                $img = $categoryImg->getImageUrl();
              } else {
                $img = $this->getSkinUrl('images/2test.jpg');
              }
              ?>
              <div class="sub-cat-one">
                <a href="<?php echo $categoryImg->getUrl() ?>">
                  <img src="<?php echo $img; ?>"
                       alt="<?php echo $categoryImg->getName() ?>">

                  <div class="pos-absolute-c"></div>
                  <p class="pos-absolute-p sub-cat-text"><?php echo $categoryImg->getName() ?></p>
                </a>
              </div>
              <?php
              $one = true;
              break;
            }

          }
          if ($two == true && $one == true) {
            break;
          }

        }
        ?>


      </div>
    </div>
  </div>
</div>

<br>
<div class="category-product">
  <div class="row">
    <div class="col-xs-12">
      <?php
      $count_product = false;
      $t = true;
      $j = 0;
      foreach ($children as $category) {
        $children1 = Mage::getModel('catalog/category')->getCategories($category->getId());
        foreach ($children1 as $category1) {
          $products = Mage::getModel('catalog/category')->load($category1->getId());

          ?>
          <?php if ($t == true) { ?>
            <div class="col-xs-12 col-sm-3">
              <div class="c-two">
                <?php
                $img = '';
                if ($products->getImageUrl()) {
                  $img = $products->getImageUrl();
                } else {
                  $img = $this->getSkinUrl('images/4test.jpg');

                }
                ?>
                <a href="<?php echo $products->getUrl() ?>">
                  <img style="max-width: 100%" src="<?php echo $img ?>"
                       alt="<?php echo $products->getName() ?>">

                  <div class="pos-absolute-c"></div>
                  <p class="pos-absolute-p sub-cat-text"><?php echo $products->getName() ?></p>
                </a>
              </div>
            </div>
            <?php
            $t = false;
          } ?>


          <?php

          $productslist = $products->getProductCollection()->addAttributeToSelect('*')
              ->addAttributeToFilter('status', 1)
              ->addAttributeToFilter('visibility', 4);

          if (count($productslist) >= 4) {
            ?>
            <div class="col-xs-12 col-sm-9">
              <div class="slider-sl">
                <?php
                foreach ($productslist as $product) { ?>
                  <div class="item">
                    <img
                        src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>"
                        alt="<?php echo $product->getName() ?>">
                    <h4 style="text-align: center">
                      <a style="font-size: 12px" href="<?php echo $product->getUrl() ?>"><?php echo $product->getName() ?></a>
                    </h4>
                  </div>
                  <?php

                  $j++;
                  if ($j == 5) {
                    $count_product = true;
                    break;
                  }
                }
                ?>
              </div>
              <script>
                jQuery(document).ready(function () {
                  jQuery('.slider-sl').owlCarousel({
                    loop:true,
                    margin:10,
                    nav:false,
                    responsive:{
                      0:{
                        items:1
                      },
                      600:{
                        items:2
                      },
                      1000:{
                        items:4
                      }
                    }
                  })
                })
              </script>
            </div>
            <?php

          } else {
            continue;
          }
          if ($count_product == true) {
            break;
          } ?>

          <?php
        }
        if ($count_product == true) {
          break;
        }
      }

      ?>

    </div>
  </div>
</div>
