<?php $_product = $this->getProduct(); ?>
<?php
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
$qty = (int)$stock->getQtyIncrements();
$class = '';
$value ='';
$valueQty = $this->getProductDefaultQty();
if($qty != 1 || $qty > 1){
    $class = 'qty_increments';
    $value = 'increments="'.$qty.'""';
    $valueQty = $qty;
} ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <?php if ($qty > 1) { ?>
        <div id="changes-price">
            <?php echo $this->getPriceHtml($_product) ?>
        </div>
        <script>
            jQuery(document).ready(function () {
                var price = jQuery('.price .price').text();
                price = price.split(',',2);
                var p = price[0];
                var vatQty = jQuery('.qty_increments #qty').val();
                var priceFinal = parseInt(p * vatQty);
                jQuery('#changes-price .price').text(priceFinal + ',00 kr');
            });
        </script>
    <?php } ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <div class="qty-holder <?php echo $class; ?>">
            <a href="javascript:void(0)" class="table_qty_dec">-</a><input <?php echo $value; ?> type="text" name="qty" id="qty" maxlength="12" value="<?php echo $valueQty * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" /><a href="javascript:void(0)" class="table_qty_inc">+</a>
        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><i class="icon-cart"></i><?php echo $buttonTitle ?></span></span></button>
        <span id='ajax_loader' style='display:none'><i class="ajax-loader small"></i></span>
		<?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
