<?php echo $this->getChildHtml('items_before'); ?>

<div id="checkout-review-table-wrapper">
    <div class="klarna_block klarna_cart col-xs-12 col-sm-8">
        <table class="table data-table" id="checkout-review-table">
            <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
            <col width="1"/>
            <col width="1"/>
            <col width="1"/>
            <col width="1"/>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1"/>
                <col width="1"/>
            <?php endif; ?>
            <col width="1"/>
            <tbody>
            <?php foreach ($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>

            </tbody>

        </table>
    </div>

    <?php echo $this->getChildHtml('totals'); ?>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">//jQuery('#checkout-review-table').decorate('table');</script>
<div id="checkout-review-submit">

</div>
<div id="checkout-paypaliframe-load" class="authentication white-popup mfp-hide"></div>
<script type="text/javascript">
    //<![CDATA[
    review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
</script>

