<div class="col-xs-12 mobile-checkout">
    <h1><?php echo $this->__('Checkout') ?></h1>

    <div class="mobile-method-checkout">
        <p style="margin-bottom: 0px"><?php echo $this->__('Please choose your'); ?></p>

        <p style="margin-top: 2px"><?php echo $this->__('checkout method'); ?></p>
    </div>
</div>
<div id="none-method" class="col-xs-12 padding-none">
    <?php
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $bool = false;
    ?>
    <?php foreach ($this->getUrls() as $key => $item): ?>
        <?php
        $class = '';
        if ($this->currentStore == $key) {
            if ($this->currentStore == 2) {
                $pos = strpos($currentUrl, 'klarna');
                if ($pos === false) {
                    $class = '';
                    $bool = true;
                } else {
                    $class = 'active';
                }
            } else {
                $class = 'active';
            }
        }
        if ($bool) {
            if ($key == 1) {
                $class = 'active';
            }
        }

        ?>
        <a class="mobile-active-checkout-method <?php echo $class; //(($this->currentStore == $key) ? 'active' : '') ?>"
           href="<?php echo $item['url'] ?>"><?php echo $item['name']; ?></a>
    <?php endforeach; ?>
</div>

<div>
    <?php foreach ($this->getUrls() as $key => $item): ?>
        <?php
        $class = '';
        if ($this->currentStore == $key) {
            if ($this->currentStore == 2) {
                $pos = strpos($currentUrl, 'klarna');
                if ($pos === false) {
                    $class = '';
                    $bool = true;
                } else {
                    $class = 'active';
                }
            } else {
                $class = 'active';
            }
        }
        if ($bool) {
            if ($key == 1) {
                $class = 'active';
            }
        }
        if ($class == 'active') {
            ?>
            <div class="col-xs-12 steps-checkout-numbers">
                <span class="span-one">1</span>
                <hr class="hr-one">
                <span class="span-two">2</span>
                <hr class="span-two">
                <span class="span-three">3</span>
                <div style="clear: both"></div>
            </div>
            <div style="clear: both"></div>
            <h2 class="mobile-name-checkout-method">
                <?php echo $item['name']; ?>
            </h2>
        <?php } ?>
    <?php endforeach; ?>
</div>

<?php
//echo Mage::app()->getRequest()->getControllerName();
//echo '<br>';
//echo Mage::app()->getRequest()->getActionName();
//echo '<br>';
//echo Mage::app()->getRequest()->getRouteName();
//echo '<br>';
//echo Mage::app()->getRequest()->getModuleName();
//echo '<br>';
//echo Mage::app()->getRequest()->getControllerModule();
?>