<?php $categoryId = $this->getCategoryId();?>

<?php
$category = Mage::getModel('catalog/category')->load($categoryId);

$storeId = Mage::app()->getStore()->getId();
$attributes = Mage::getSingleton('catalog/config')->getProductAttributes();

$collection = Mage::getModel('catalog/product')->getCollection()
    ->addAttributeToSelect($attributes)
    ->addMinimalPrice()
    ->addFinalPrice()
    ->addTaxPercents()
    ->addCategoryFilter($category)
    ->addAttributeToFilter('status', 1);

Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);

$collection->setPageSize($this->getConfig('qty'))->setCurPage(10);
Mage::getModel('review/review')->appendSummary($collection);

?>
<?php

?>

<div class="inspiration-product">
    <?php
    foreach($collection as $_product){ ?>
        <?php
        $product = Mage::getModel('catalog/product')->load($_product->getId());
        ?>
        <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="item-area">
                <div class="product-image-area">
                    <?php if (Mage::getStoreConfig("mango_settings/category/actions", $code)): ?>
                        <div class="actions">
                            <?php if ($_product->isSaleable()): ?>
                                <?php if (!($_product->getTypeInstance(true)->hasOptions($_product)/*$_product->getData('has_options')*/ || $_product->isGrouped())) : ?>
                                    <a href="<?php if (Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)): ?>javascript:setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>"
                                       class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i
                                                class="icon-mango-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
                                <?php else : ?>
                                    <a href="<?php if (Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)): ?>javascript:showOptions('<?php echo $_product->getId() ?>')<?php else: ?><?php echo $this->getAddToCartUrl($_product) ?><?php endif; ?>"
                                       class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i
                                                class="icon-mango-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></a>
                                    <a href='<?php echo $this->getUrl('ajaxcart/index/options', array('product_id' => $_product->getId())); ?>'
                                       class='fancybox' id='fancybox<?php echo $_product->getId() ?>'
                                       style='display:none'>Options</a>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php if (Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)): ?>javascript:ajaxWishlist('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>','<?php echo $_product->getId() ?>');<?php else: ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>"
                                   class="addtowishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i
                                            class="icon-mango-heart"></i></a>
                            <?php endif; ?>
                            <?php if (Mage::getStoreConfig("mango_settings/category/compare", $code) && $_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php if (Mage::getStoreConfig("ajaxcart/addtolinks/enablecategory", $code)): ?>javascript:ajaxCompare('<?php echo $_compareUrl ?>','<?php echo $_product->getId() ?>');<?php else: ?><?php echo $_compareUrl ?><?php endif; ?>"
                                   class="comparelink" title="<?php echo $this->__('Add to Compare') ?>"><i
                                            class="icon-mango-compare"></i></a>
                            <?php endif; ?>
                            <?php
                            if (Mage::getStoreConfig("quickview/general/enableview", $code)) {
                                $base_url = $this->getUrl();
                                if (strpos($base_url, '?') !== false)
                                    $base_url = explode("?", $this->getUrl());
                                if (is_array($base_url))
                                    $base_url = $base_url[0];
                                $base_url .= "quickview/index/view/";
                                $quickview_url = $base_url . "id/" . $_product->getId();
                                ?>
                                <a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i
                                            class="icon-mango-quickview"></i><span><?php echo $this->__("Quick View"); ?></span></a>
                                <?php
                            }
                            ?>
                        </div>
                    <?php endif; ?>
                    <?php if (!$effect): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <img src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                    <?php elseif ($effect == "alternative"): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php if ($_product->getSmallImage() == $_product->getThumbnail()) { ?>
                                <img class="defaultImage"
                                     src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php } else { ?>
                                <img class="defaultImage"
                                     src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                <img class="hoverImage"
                                     src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>
                            <?php } ?>
                        </a>
                    <?php elseif ($effect == "gallery"): ?>
                        <?php
                        $product = Mage::getModel('catalog/product')->load($_product->getId());
                        $gallery_images = $product->getMediaGalleryImages();
                        ?>
                        <?php if (count($gallery_images) < 1): ?>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                               class="product-image">
                                <img src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            </a>
                        <?php else: ?>
                            <div class="owl-product-image-gallery owl-carousel">
                                <?php foreach ($gallery_images as $image): ?>
                                    <?php // If no image, skip
                                    if ($image->getFile() == NULL)
                                        continue;
                                    ?>
                                    <div class="item">
                                        <a href="<?php echo $_product->getProductUrl() ?>"
                                           title="<?php echo $this->escapeHtml($image->getLabel()) ?>"
                                           class="product-image">
                                            <img src="<?php if ($aspect_ratio): ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $image->getFile())->resize($ratio_width, $ratio_height); ?><?php endif; ?>"
                                                 alt="<?php echo $this->escapeHtml($image->getLabel()) ?>"/>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php

                    $sale_label = false;
                    // Get the Special Price
                    $specialprice = $product->getFinalPrice();
                    $orgprice = $product->getPrice();
                    // Get the Special Price FROM date
                    $specialPriceFromDate = $product->getSpecialFromDate();
                    // Get the Special Price TO date
                    $specialPriceToDate = $product->getSpecialToDate();
                    // Get Current date
                    $today = time();

                    if ($specialprice < $orgprice) {
                        $save_percent = 100 - round(($specialprice / $orgprice) * 100);
                        if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
                            if (Mage::getStoreConfig("mango_settings/product_label/sale", $code)) {
                                $sale_label = true;
                                ?>
                                <div class="product-label" style="left: 7px;"><span
                                            class="sale-product-icon"><?php if (Mage::getStoreConfig("mango_settings/product_label/sale_label_type", $code)): ?><?php echo "-" . $save_percent . "%"; ?><?php else: ?><?php echo Mage::getStoreConfig("mango_settings/product_label/sale_label_text", $code); ?><?php endif; ?></span>
                                </div>
                                <?php
                            }
                        }
                    }
                    ?>
                    <?php
                    $now = date("Y-m-d");
                    $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                    $newsTo = substr($_product->getData('news_to_date'), 0, 10);
                    if ($newsTo != '' || $newsFrom != '') {
                        if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
                            if (Mage::getStoreConfig("mango_settings/product_label/new", $code)) {
                                ?>
                                <div class="product-label" style="right: 7px;"><span
                                            class="new-product-icon"><?php echo Mage::getStoreConfig("mango_settings/product_label/new_label_text", $code); ?></span>
                                </div>
                                <?php
                            }
                        }
                    }
                    ?>
                </div>
                <div class="details-area">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName();?></a>
                    </h2>

                    <?php if (Mage::getStoreConfig("mango_settings/category/product_price", $code)): ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<style>
    .page {
        background-color: #000;
    }
    .item-area{
        background-color: #fff;
        padding-bottom: 10px;
    }
    .product-image-area {
        padding: 0 25px;
    }

    .item-area .product-image-area .actions > a.addtocart {
        text-align: right;
    }

    .inspiration-product .col-xs-12{
        margin-bottom: 25px;
    }

</style>